DROP SCHEMA IF EXISTS cinema CASCADE ;
CREATE SCHEMA IF NOT EXISTS cinema;

DROP TABLE IF EXISTS cinema.users;
CREATE TABLE IF NOT EXISTS cinema.users(
    user_id SERIAL PRIMARY KEY,
    login   VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(100) NOT NULL
);

